-- ============================================
-- MILO: Scrape & Sync Migration
-- Adds source_url column for deduplication.
-- Run in Supabase Dashboard → SQL Editor
-- ============================================
