export interface EventData {
  id: string;
  name: string;
  category: string;
  image: string;
  cityId: string;
  description: string;
  price: string;
  color: string;
  featured?: boolean;
}

export const EVENTS: EventData[] = [
  // Delhi Events (10)
  {
    id: "del-1",
    name: "Lotus Temple Gala",
    category: "CULTURE / ARTS",
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=800",
    cityId: "del",
    description: "An evening of traditional music and arts at the iconic Lotus Temple architecture.",
    price: "₹1,499",
    color: "#a855f7",
    featured: true,
  },
  {
    id: "del-2",
    name: "Neon Delhi Night",
    category: "MUSIC / TECH",
    image: "https://images.unsplash.com/photo-1524492459423-47620df35f2a?auto=format&fit=crop&q=80&w=800",
    cityId: "del",
    description: "Futuristic electronic beats set against the historic backdrop of the Qutub Minar.",
    price: "₹2,999",
    color: "#a855f7",
  },
  {
    id: "del-3",
    name: "Hauz Khas Pulse",
    category: "COMMUNITY / TECH",
    image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&q=80&w=800",
    cityId: "del",
    description: "The capital's biggest outdoor tech mixer in the heart of old Delhi.",
    price: "₹899",
    color: "#a855f7",
  },
  {
    id: "del-4",
    name: "Qutub Jazz Fusion",
    category: "MUSIC / JAZZ",
    image: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&q=80&w=800",
    cityId: "del",
    description: "A blend of traditional jazz and Indian classical instruments under the starlit minar.",
    price: "₹2,200",
    color: "#a855f7",
  },
  {
    id: "del-5",
    name: "Cyber Chandni Chowk",
    category: "STREET / TECH",
    image: "https://images.unsplash.com/photo-1552533685-685846395376?auto=format&fit=crop&q=80&w=800",
    cityId: "del",
    description: "AR-guided walk through the historic lanes of Old Delhi with hidden digital treasures.",
    price: "₹599",
    color: "#a855f7",
  },
  {
    id: "del-6",
    name: "India Gate Vapor",
    category: "ARTS / INSTALLATION",
    image: "https://images.unsplash.com/photo-1570160897040-3043bae3b8c1?auto=format&fit=crop&q=80&w=800",
    cityId: "del",
    description: "A massive projection mapping show on the memorial arch celebrating the city's future.",
    price: "₹1,100",
    color: "#a855f7",
  },
  {
    id: "del-7",
    name: "Red Fort AI Gala",
    category: "TECH / HISTORY",
    image: "https://images.unsplash.com/photo-1564507004663-b6dfb3c824d5?auto=format&fit=crop&q=80&w=800",
    cityId: "del",
    description: "Artificial intelligence reimagining the Mughal history through immersive 3D headsets.",
    price: "₹1,800",
    color: "#a855f7",
    featured: true,
  },
  {
    id: "del-8",
    name: "New Delhi Beats",
    category: "MUSIC / POP",
    image: "https://images.unsplash.com/photo-1514525253344-934d701df637?auto=format&fit=crop&q=80&w=800",
    cityId: "del",
    description: "Contemporary pop festival featuring the top regional and global artists.",
    price: "₹4,500",
    color: "#a855f7",
  },
  {
    id: "del-9",
    name: "Yamuna Vapor Trail",
    category: "ENV / TECH",
    image: "https://images.unsplash.com/photo-1506466010722-395aa2bef877?auto=format&fit=crop&q=80&w=800",
    cityId: "del",
    description: "Laser and water show on the banks of Yamuna focusing on ecological restoration.",
    price: "₹700",
    color: "#a855f7",
  },
  {
    id: "del-10",
    name: "Dilli Haat Cyber",
    category: "STREET / FOOD",
    image: "https://images.unsplash.com/photo-1505245208461-bc4ccff88fbd?auto=format&fit=crop&q=80&w=800",
    cityId: "del",
    description: "Fusion food festival where traditional recipes are optimized by AI chefs.",
    price: "₹1,200",
    color: "#a855f7",
  },

  // Bangalore Events (10)
  {
    id: "blr-1",
    name: "Matrix Hackathon",
    category: "TECH / EXPO",
    image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=800",
    cityId: "blr",
    description: "The city's biggest 48-hour coding sprint inside the digital gardens of Bangalore.",
    price: "₹499",
    color: "#22c55e",
    featured: true,
  },
  {
    id: "blr-2",
    name: "Green Valley Beats",
    category: "MUSIC / FEST",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=800",
    cityId: "blr",
    description: "Eco-friendly open-air music festival celebrating the Garden City's vibrant spirit.",
    price: "₹1,899",
    color: "#22c55e",
    featured: true,
  },
  {
    id: "blr-3",
    name: "Indira Nagar Expo",
    category: "TECH / EXPO",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=800",
    cityId: "blr",
    description: "Future showcase for sustainable urban planning in Bangalore.",
    price: "₹1,200",
    color: "#22c55e",
  },
  {
    id: "blr-4",
    name: "Lalbagh AI Expo",
    category: "SCIENCE / BOTANY",
    image: "https://images.unsplash.com/photo-1453722758971-da0f4c017366?auto=format&fit=crop&q=80&w=800",
    cityId: "blr",
    description: "Witness the integration of robotic life monitoring within the historic glass house.",
    price: "₹750",
    color: "#22c55e",
  },
  {
    id: "blr-5",
    name: "Cyber Garden Rave",
    category: "MUSIC / ELECTRONIC",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=800",
    cityId: "blr",
    description: "An underground electronic session set in a decommissioned warehouse turned garden.",
    price: "₹2,500",
    color: "#22c55e",
  },
  {
    id: "blr-6",
    name: "Silicon Hub Summit",
    category: "TECH / BUSINESS",
    image: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&q=80&w=800",
    cityId: "blr",
    description: "Networking event for the top 500 startups in the country's tech capital.",
    price: "₹5,000",
    color: "#22c55e",
  },
  {
    id: "blr-7",
    name: "Cubbon Park VR",
    category: "NATURE / TECH",
    image: "https://images.unsplash.com/photo-1501333198491-3cd637508655?auto=format&fit=crop&q=80&w=800",
    cityId: "blr",
    description: "A virtual reality walk through the prehistoric forests that preceded Bangalore.",
    price: "₹300",
    color: "#22c55e",
  },
  {
    id: "blr-8",
    name: "Koramangala Pulse",
    category: "COMMUNITY / ARTS",
    image: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&q=80&w=800",
    cityId: "blr",
    description: "Street mural festival where technology informs the art style of the local neighborhood.",
    price: "₹200",
    color: "#22c55e",
  },
  {
    id: "blr-9",
    name: "Electronic City Expo",
    category: "TECH / ROBOTICS",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=800",
    cityId: "blr",
    description: "The grand showcase of humanoid automation developed in the silicon heartland.",
    price: "₹1,500",
    color: "#22c55e",
    featured: true,
  },
  {
    id: "blr-10",
    name: "Bangalore Indie Fest",
    category: "MUSIC / INDIE",
    image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&q=80&w=800",
    cityId: "blr",
    description: "Celebrating the local indie music scene with innovative digital audio installations.",
    price: "₹699",
    color: "#22c55e",
  },

  // Mumbai Events (10)
  {
    id: "mum-1",
    name: "Cyber Gateway Gala",
    category: "FASHION / TECH",
    image: "https://images.unsplash.com/photo-1570160897040-3043bae3b8c1?auto=format&fit=crop&q=80&w=800",
    cityId: "mum",
    description: "A high-fashion runway event utilizing the Gateway of India as a digital canvas.",
    price: "₹3,500",
    color: "#06b6d4",
    featured: true,
  },
  {
    id: "mum-2",
    name: "Marine Drive Vapor",
    category: "CINEMA / ARTS",
    image: "https://images.unsplash.com/photo-1566552881560-0be862a7c445?auto=format&fit=crop&q=80&w=800",
    cityId: "mum",
    description: "Immersive open-air cinema screen experience right on the shores of Marine Drive.",
    price: "₹1,200",
    color: "#06b6d4",
  },
  {
    id: "mum-3",
    name: "Juhu Art Wave",
    category: "ARTS / TECH",
    image: "https://images.unsplash.com/photo-1514525253344-934d701df637?auto=format&fit=crop&q=80&w=800",
    cityId: "mum",
    description: "Interactive AI paintings generated by the coastline's tidal waves.",
    price: "₹2,500",
    color: "#06b6d4",
    featured: true,
  },
  {
    id: "mum-4",
    name: "Bandra Cyber Punk",
    category: "MUSIC / INDIE",
    image: "https://images.unsplash.com/photo-1557683311-eac922347aa1?auto=format&fit=crop&q=80&w=800",
    cityId: "mum",
    description: "An experimental music night exploring the intersections of indie jazz and glitch-hop.",
    price: "₹1,800",
    color: "#06b6d4",
  },
  {
    id: "mum-5",
    name: "Colaba Retro Future",
    category: "ANTIQUE / TECH",
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&q=80&w=800",
    cityId: "mum",
    description: "A rare collection of vintage tech restored and automated with modern AI.",
    price: "₹900",
    color: "#06b6d4",
  },
  {
    id: "mum-6",
    name: "Worli Sea Sprints",
    category: "TECH / SPORTS",
    image: "https://images.unsplash.com/photo-1544117519-31a4b719223d?auto=format&fit=crop&q=80&w=800",
    cityId: "mum",
    description: "Electric hydrofoil boat racing under the Worli Sea Link.",
    price: "₹3,999",
    color: "#06b6d4",
  },
  {
    id: "mum-7",
    name: "Dharavi Tech Hub",
    category: "TECH / COMMUNITY",
    image: "https://images.unsplash.com/photo-1518349619113-03114f06ac3a?auto=format&fit=crop&q=80&w=800",
    cityId: "mum",
    description: "A showcase of grassroots technological innovation and recycling within the city.",
    price: "FREE",
    color: "#06b6d4",
  },
  {
    id: "mum-8",
    name: "Powai Nebula Expo",
    category: "TECH / EXPO",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800",
    cityId: "mum",
    description: "Interactive data visualization of the world's oceans shown inside the Powai hub.",
    price: "₹500",
    color: "#06b6d4",
    featured: true,
  },
  {
    id: "mum-9",
    name: "South Bombay Vapor",
    category: "ARTS / CULTURE",
    image: "https://images.unsplash.com/photo-1513829596324-4bb2800c5efb?auto=format&fit=crop&q=80&w=800",
    cityId: "mum",
    description: "Exploring the colonial architecture of South Mumbai through a digital lens.",
    price: "₹1,500",
    color: "#06b6d4",
  },
  {
    id: "mum-10",
    name: "Gateway Art Flow",
    category: "ARTS / MUSIC",
    image: "https://images.unsplash.com/photo-1493225255756-d9584f8606e9?auto=format&fit=crop&q=80&w=800",
    cityId: "mum",
    description: "Closing gala event at the Gateway featuring a massive orchestra and light show.",
    price: "₹5,000",
    color: "#06b6d4",
  },

  // Global / Generic
  {
    id: "gen-1",
    name: "Identity Scan Beta",
    category: "COMMUNITY / TECH",
    image: "https://images.unsplash.com/photo-1614850715649-1d01062939a4?auto=format&fit=crop&q=80&w=800",
    cityId: "all",
    description: "Participate in the global Milo identity scan beta testing session.",
    price: "FREE",
    color: "#FFFFFF",
    featured: true,
  },
  {
    id: "gen-2",
    name: "Event Nebula Expo",
    category: "TECH / EXPO",
    image: "https://images.unsplash.com/photo-1540575861501-7c00117ff64b?auto=format&fit=crop&q=80&w=800",
    cityId: "all",
    description: "A glimpse into the future of 3D event discovery and immersive networking.",
    price: "₹999",
    color: "#FFFFFF",
  }
];
